### ISSUE TITLE
Extend README with related works and applications

### ISSUE THREAD

**Issue by nichtich** [lszeremeta/yarspg#101]
The README file should include some information about motivation, related works, and application of YARS-PG. So far I found
http://dx.doi.org/10.13140/RG.2.2.35773.92640 (the original poster from 2019, describing YARS-PG 3.0.0?). https://github.com/gkellogg/yarspg (seems to use version 3.0.0 as well), and https://doi.org/10.6084/m9.figshare.25139015.v1 (some actual data in YARS-PG). Are there more applications and examples to try out and test against?

**Comment by lszeremeta** [comment]
Hi! :wave: 
Yes, I planned to provide at least a link to a more detailed description of the current version of YARS-PG when it will be public and preferably expand the README even further. Unfortunately, you'll have to wait a while for it, but it's definitely closer than farther, probably will be in May :slightly_smiling_face:

**Comment by lszeremeta** [comment]
Hi @nichtich,
I don't know if you noticed, but I added a link to the repository with our paper about the new version of YARS-PG. You can read it here: https://ieeexplore.ieee.org/document/10536116

**Comment by lszeremeta** [comment]
I also improved the README :slightly_smiling_face:

**Comment by nichtich** [comment]
@lszeremeta Thanks, great paper! Looks we've been a little bit too late with [Property Graph Exchange Format (PG)](https://pg-format.github.io/) to get mentioned. We're going to finish [stable version 1.0.0](https://pg-format.github.io/specification/) this summer and look at extensions such as graph schemas and metadata afterwards.

**Comment by lszeremeta** [comment]
@nichtich Yes, definitely. I sent the paper to the journal on February 11, and sometime before sending it, we just improved it. I wanted it to be as polished as possible before sending it, and it seems it was - the paper was accepted in the first round 🙂 I will try to follow your works with the Property Graph Exchange Format (PG). Thank you for sharing! 🙂

**Comment by nichtich** [comment]
FYI I've translated the YARS-PG Listing 1 from the paper [to PG format](https://pg-format.github.io/pg-formatter/?url=https://raw.githubusercontent.com/g2glab/pg-formatter/main/examples/yars-pg.pg) for comparison. Translation back to YARS-PG requires https://github.com/pg-format/pgraphs/issues/28 (=NodeJS implementation of YARS-PG parser and writer).
