### ISSUE TITLE
Broaden range of allowed identifiers

### ISSUE THREAD

**Issue by nichtich** [lszeremeta/yarspg#86]
YARS-PG 3.0.0 allowed arbitrary strings as node identifiers. With YARS-PG 4.0.0 this has been limited to `ALNUMPLUS`: 

~~~
node_id
    : ALNUMPLUS   
    ;

ALNUMPLUS
    : [a-zA-Z_][a-zA-Z0-9_]*
~~~

I'd support arbitrary quoted strings

~~~
node_id
    : ALNUMPLUS
    | STR   
    ;
~~~

or at least numbers

~~~
node_id
    : ALNUMPLUS
    | UNSIGNED_INT   
    ;
~~~

**Comment by lszeremeta** [comment]
Hi, thank you for the suggestion.

YARS-PG 4 introduced many changes. New capabilities have been added, and we've also redesigned the syntax to ensure greater readability and the possibility of compression.

Identifiers in YARS-PG 4 were inspired by [xml:id](https://www.w3.org/TR/xml-id/), where a number cannot appear first. Identifiers are one of the few elements in YARS-PG 4 without quotes. The absence of quotes suggests no spaces. This change was motivated by readability, and overall, we considered that identifiers with letters, numbers, and `_` are sufficient.

Numbers in identifiers are supported; it's just that the first character must be a letter or `_`, similar to [xml:id](https://www.w3.org/TR/xml-id/).

We do not plan to change this aspect for now, but we will keep your feedback in mind for further work.

Thanks! :+1:

**Comment by nichtich** [comment]
Thanks for the quick feedback! If identifiers are not meant to be preserved across applications, it's ok to have different kinds of restrictions on these identifier. I'll just map existing node ids to new identifiers `node1`, `node2`... when creating YARS-PG.

**Comment by lszeremeta** [comment]
From your reply, it seems that you are using YARS-PG. May I know for what exactly? I'm just curious 🙂
