### ISSUE TITLE
Disallow leading zeroes in UNSIGNED_INT

### ISSUE THREAD

**Issue by nichtich** [lszeremeta/yarspg#87]
Change 

~~~
UNSIGNED_INT
    : [0-9]+
    ;
~~~

to

~~~
UNSIGNED_INT
    : "0" | [1-9] [0-9]*
    ;
~~~

**Comment by lszeremeta** [comment]
Hi, thank you for your suggestion.

You are right. `UNSIGNED_INT` in YARS-PG  is used for cardinalities, datatype precision, and datatype scale. Leading zeros are not needed here, and the allowance to add them may introduce confusion.

I fixed it in 1dea9e3946c285c2fbd08bb87a839784a6709ade, and I released the [YARS-PG 5.0.0](https://github.com/lszeremeta/yarspg/releases/tag/v5.0.0) based on semantic versioning ("incompatible API changes").
